---
- hosts: web
  become: yes
  tasks:
  - name: Устанавливаем Mutt
    yum:
      name:
        mutt

  - name: Отправляем письмо
    mail:
      host: 172.20.10.50
      port: 25
      to: Vagrant Otus <vagrant@otus.local>
      subject: Тестовое Письмо
      body: System {{ ansible_hostname }} отправила вам письмо.